[Service]
Environment=GPU_MESH_DB=/var/lib/mycellios/mycellios.db
Environment=MYCELLIOS_NODE_UPDATES_DIST=/var/lib/mycellios/node-updates
Environment=MYCELLIOS_DOWNLOADS_DIST=/var/lib/mycellios/downloads
Environment=MYCELLIOS_BENCHMARK_ROOT=/var/lib/mycellios/benchmarks
