[Service]
Environment=MYCELLIOS_DESKTOP_UPDATES_DIST=/var/lib/mycellios/desktop-updates
Environment=MYCELLIOS_DOWNLOADS_DIST=/var/lib/mycellios/downloads
Environment=MYCELLIOS_BENCHMARK_ROOT=/var/lib/mycellios/benchmarks
